# Happy reminder: THIS HAS TO BE BACKWARDS COMPATIBLE WITH ANSIBLE ALL THE WAY TO 1.5

## We assume that hub-pull will run on a already configured hub,
## that will have recent versions of git and pip
# - name: install dependencies
#   apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
#   sudo: yes
#   with_items:
#     - git
#     - python-pip

- include: not_pulling.yml
  when: pulling == false

- name: cache the github.com host key
  shell: creates="{{ home }}/.ssh/.cached-host-key-github.com"
      ssh-keyscan -t ecdsa,rsa,dsa github.com >> ~/.ssh/known_hosts;
      touch {{ home }}/.ssh/.cached-host-key-github.com

- name: checkout the blobs repo
  git: dest={{ blobs }} repo={{ blobs_repo }} depth=1 version={{ blobs_rev }}
- name: install ansible
  pip: name=ansible version=1.5.3
      extra_args="--no-index --use-wheel --find-links={{ blobs }}/wheelhouse"
  sudo: yes

- name: copy ansible inventory file
  copy: src=local_inventory.ini dest={{ home }}/inventory.ini mode=0644

- name: mkdir
  file: path={{ deploy }} state=directory

- name: upload ansible-pull.sh
  template: src=ansible-pull.sh dest="{{ home }}/ansible-pull.sh" mode=0755

- name: create cron entries
  cron: name="run ansible-pull" minute="*/15" job="{{ home }}/ansible-pull.sh"
  # TODO: better ansible-pull run-on-updates strategy
